/**
 * Subscription Flow Tests
 *
 * Tests real plan selection and switching flows using the test data API
 * to create/delete plans and set tenant plans directly.
 *
 * Unlike subscription-plans.spec.ts (which uses API mocking), these tests
 * hit the real API to verify the end-to-end UX.
 *
 * Test scenarios:
 * 1. Select a free plan via the PlanSelector UI → lands on /subscription/success
 * 2. Switch from one plan to another via the UI → lands on /subscription/success
 * 3. (Optional) Stripe checkout is triggered for a paid plan when Stripe is configured
 */

import { test, expect } from '../../fixtures/auth';
import type { Page } from '@playwright/test';
import { MED_TIMEOUT, LONG_TIMEOUT } from '../../fixtures/timeouts';

/**
 * TBP-743 — picking a plan (free, or a switch that needs no checkout) goes on
 * to `/subscription/success`, the page a completed Stripe checkout returns to.
 * It used to leave the person on the picker, looking as if nothing happened
 * (TBP-762). Asserts the page, its heading, and that it names `planName`.
 */
async function expectSuccessPageFor(page: Page, planName: string): Promise<void> {
  await page.waitForURL('**/subscription/success', { timeout: LONG_TIMEOUT });
  const success = page.locator('[data-bridge-billing-route="success"]');
  await expect(success.getByRole('heading', { name: "You're all set" })).toBeVisible({
    timeout: MED_TIMEOUT,
  });
  await expect(success.locator('.bss-plan')).toHaveText(planName, { timeout: LONG_TIMEOUT });
}

// Keys generated by Stripe test mode — skip Stripe tests if not set
const STRIPE_TEST_PK = process.env.STRIPE_TEST_PK || '';
const STRIPE_TEST_SK = process.env.STRIPE_TEST_SK || '';
const hasStripeKeys = !!STRIPE_TEST_PK && !!STRIPE_TEST_SK;

test.describe('Subscription Flows', () => {
  test('select a free plan via PlanSelector UI', async ({
    authenticatedPage,
    testUser,
    testDataClient,
  }) => {
    const page = authenticatedPage;
    const planKey = `free-e2e-${Date.now()}`;

    try {
      // Create a free plan via the API
      await testDataClient.createPlan({
        key: planKey,
        name: 'Free E2E',
        description: 'Free plan created by E2E test',
        prices: [{ amount: 0, currency: 'USD', recurrenceInterval: 'month' }],
      });

      await page.goto('/subscription');
      await page.waitForURL('**/subscription**', { timeout: MED_TIMEOUT });

      const planSelector = page.locator('[data-bridge-plan-selector]');
      await expect(planSelector).toBeVisible({ timeout: MED_TIMEOUT });

      // Wait for loading to complete
      await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
        timeout: LONG_TIMEOUT,
      });

      // Find THIS test's free plan card and click "Select free plan". The app
      // can carry other free plans (e.g. "Free"), so pick the card by name.
      const selectBtn = page
        .locator('[data-bridge-plan-card]')
        .filter({ hasText: 'Free E2E' })
        .locator('button:has-text("Select free plan")')
        .first();
      await expect(selectBtn).toBeVisible({ timeout: MED_TIMEOUT });
      await selectBtn.click();

      // TBP-743 / TBP-762 — a free pick goes on to the success page, exactly
      // like a completed checkout does, and that page names the new plan.
      await expectSuccessPageFor(page, 'Free E2E');

      // Back on the picker, the plan just chosen is the current one.
      await page.goto('/subscription');
      await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
        timeout: LONG_TIMEOUT,
      });
      const currentPlanBtn = page
        .locator('[data-bridge-plan-card][data-current="true"] button')
        .first();
      await expect(currentPlanBtn).toBeVisible({ timeout: MED_TIMEOUT });
      const btnText = await currentPlanBtn.textContent();
      expect(btnText?.trim()).toContain('Current plan');
    } finally {
      await testDataClient.deletePlan(planKey).catch(() => {});
    }
  });

  test('switch from plan A to plan B via PlanSelector UI', async ({
    authenticatedPage,
    testUser,
    testDataClient,
  }) => {
    const page = authenticatedPage;
    const planAKey = `plan-a-e2e-${Date.now()}`;
    const planBKey = `plan-b-e2e-${Date.now()}`;

    try {
      // Create two free plans
      await testDataClient.createPlan({
        key: planAKey,
        name: 'Plan A',
        description: 'Plan A for switching test',
        prices: [{ amount: 0, currency: 'USD', recurrenceInterval: 'month' }],
      });
      await testDataClient.createPlan({
        key: planBKey,
        name: 'Plan B',
        description: 'Plan B for switching test',
        prices: [{ amount: 0, currency: 'USD', recurrenceInterval: 'month' }],
      });

      // Pre-select Plan A via the API so we start from a known state
      await testDataClient.setTenantPlan(testUser.tenantId, planAKey);

      await page.goto('/subscription');
      await page.waitForURL('**/subscription**', { timeout: MED_TIMEOUT });

      const planSelector = page.locator('[data-bridge-plan-selector]');
      await expect(planSelector).toBeVisible({ timeout: MED_TIMEOUT });
      await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
        timeout: LONG_TIMEOUT,
      });

      // Plan A should be the current plan
      const planACard = page.locator(`[data-bridge-plan-card][data-current="true"]`);
      await expect(planACard).toContainText('Plan A', { timeout: MED_TIMEOUT });

      // Find Plan B's card by name (the app can carry other plans too) and
      // click its select button
      const planBCard = page
        .locator('[data-bridge-plan-card][data-current="false"]')
        .filter({ hasText: 'Plan B' })
        .first();
      await expect(planBCard).toBeVisible({ timeout: MED_TIMEOUT });
      const planBBtn = planBCard.locator('button').first();
      await expect(planBBtn).toBeVisible({ timeout: MED_TIMEOUT });
      await planBBtn.click();

      // TBP-743 / TBP-762 — the switch lands on the success page, naming Plan B.
      await expectSuccessPageFor(page, 'Plan B');

      // Back on the picker, Plan B is the current plan.
      await page.goto('/subscription');
      await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
        timeout: LONG_TIMEOUT,
      });
      const newCurrentCard = page.locator('[data-bridge-plan-card][data-current="true"]');
      await expect(newCurrentCard).toContainText('Plan B', { timeout: MED_TIMEOUT });
    } finally {
      await testDataClient.deletePlan(planAKey).catch(() => {});
      await testDataClient.deletePlan(planBKey).catch(() => {});
    }
  });

  test('subscription state is reflected in plan selector data-state', async ({
    authenticatedPage,
    testUser,
    testDataClient,
  }) => {
    const page = authenticatedPage;

    await page.goto('/subscription');
    await page.waitForURL('**/subscription**', { timeout: MED_TIMEOUT });

    const planSelector = page.locator('[data-bridge-plan-selector]');
    await expect(planSelector).toBeVisible({ timeout: MED_TIMEOUT });
    await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
      timeout: LONG_TIMEOUT,
    });

    // data-state should be one of the valid states
    const state = await planSelector.getAttribute('data-state');
    expect([
      'idle',
      'select-plan',
      'active',
      'trial',
      'payment-failed',
      'setup-payments',
    ]).toContain(state);
  });

  test('set-plan via API is reflected in plan selector UI', async ({
    authenticatedPage,
    testUser,
    testDataClient,
  }) => {
    const page = authenticatedPage;
    const planKey = `reflect-e2e-${Date.now()}`;

    try {
      await testDataClient.createPlan({
        key: planKey,
        name: 'Reflect Plan',
        prices: [{ amount: 0, currency: 'USD', recurrenceInterval: 'month' }],
      });

      // Set plan directly via API
      await testDataClient.setTenantPlan(testUser.tenantId, planKey);

      await page.goto('/subscription');
      await page.waitForURL('**/subscription**', { timeout: MED_TIMEOUT });

      const planSelector = page.locator('[data-bridge-plan-selector]');
      await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
        timeout: LONG_TIMEOUT,
      });

      // The plan card for this plan should be marked as current
      const currentCard = page.locator('[data-bridge-plan-card][data-current="true"]');
      await expect(currentCard).toBeVisible({ timeout: MED_TIMEOUT });
    } finally {
      await testDataClient.deletePlan(planKey).catch(() => {});
    }
  });

  test('paid plan triggers Stripe checkout redirect', async ({
    authenticatedPage,
    testUser,
    testDataClient,
    envConfig,
  }) => {
    test.skip(!hasStripeKeys, 'STRIPE_TEST_PK / STRIPE_TEST_SK not set — skipping');
    const page = authenticatedPage;
    const planKey = `stripe-e2e-${Date.now()}`;

    try {
      // Enable Stripe on the app
      await testDataClient.configureApp({
        stripeEnabled: true,
        stripePublicKey: STRIPE_TEST_PK,
        stripeSecretKey: STRIPE_TEST_SK,
        currency: 'USD',
      });

      await testDataClient.createPlan({
        key: planKey,
        name: 'Stripe Pro',
        description: 'Paid plan for Stripe E2E',
        prices: [{ amount: 2900, currency: 'USD', recurrenceInterval: 'month' }],
      });

      await page.goto('/subscription');
      await page.waitForURL('**/subscription**', { timeout: MED_TIMEOUT });

      const planSelector = page.locator('[data-bridge-plan-selector]');
      await expect(planSelector).not.toHaveAttribute('data-loading', 'true', {
        timeout: LONG_TIMEOUT,
      });

      // Click the paid plan button — target the Stripe Pro card specifically
      const stripePlanCard = page.locator('[data-bridge-plan-card]').filter({ hasText: 'Stripe Pro' });
      await expect(stripePlanCard).toBeVisible({ timeout: MED_TIMEOUT });
      const paidBtn = stripePlanCard.locator('button').first();
      await expect(paidBtn).toBeVisible({ timeout: MED_TIMEOUT });
      await paidBtn.click();

      // Should be redirected to Stripe checkout (stripe.com domain)
      await page.waitForURL((url) => url.hostname.includes('stripe.com'), {
        timeout: LONG_TIMEOUT,
      });

      expect(page.url()).toContain('stripe.com');
    } finally {
      await testDataClient.deletePlan(planKey).catch(() => {});
      // Disable Stripe again
      await testDataClient.configureApp({ stripeEnabled: false }).catch(() => {});
    }
  });
});
